#+TITLE: Clase 04 - Indices

#+BEGIN_COMMENT
Dudas..!
1. Página 11: POrque la función hash guarda especificamente en una *posición relativa*?
  tiene que ver con la pag. 19, que habla de los *indices fisicos*?
1. Pagina 16: Menciona la H, está realizando una *secuenca de incrementos* ?
   (en la ppt de metodos de clasificación aparece, en la pag. 19)
   (si no me equivoco es el tema de recurrencia de discreta)
2. Pag. 17.: Porque en el *hashing doble* si este arroja un valor negativo haría un loop infinito?
porque luego produciria numeros negativos tan grandes, y nunca llegaria a ser positivo?
3. Pag. 19: El debe ser *balanceado* para hacer menos consultas por eso minimiza las operaciones?
   en que otra ppt lo decia?

#+END_COMMENT
* [TODO] Indices
** conceptos
  - tener índices, NO quiere decir que los datos estén ordenados
  - por lo general los archivos se guardan de forma secuencial
  - es otra estructura, para acceder más rapido a los datos
    (similar a un acceso directo)
  - para no tener que evaluar dato por dato de manera secuencial
  - 
** almacenamiento
** tipos de acceso
*** secuencial
    - es recorrer un conjunto de datos uno atrás del otro 1,2,3...
    - los indices evitaran esto, porque es lento
*** secuencial indexada
    - 
*** directo o random
    - acceder de forma directa, sin pasar por los elementos anteriores
    - Ej. cuando usamos fseek en C, para acceder a una parte
      específica
** métodos para crear índices
*** hashing
*** árbol b
** [TODO] ???
** hashing
*** hashing doble
